### ISSUE TITLE
Multiple publishers question

### ISSUE THREAD

**Issue by Sjackson0** [asmecher/plagiarism#14]
Is there an update coming in the future  to ensure a publisher only has access to their journal? We have 1 OJS application with multiple journals and publishers. Since there would need to be a main account if I'm understanding correctly? We wouldn't be able to control who sees what.

**Comment by asmecher** [comment]
@Sjackson0, could you describe in more detail...
1) what you are currently experiencing,
2) what the problem with it is, and
3) what solution you might propose?

Also please include what version of OJS you're using.

**Comment by Sjackson0** [comment]
I have a  journal who would like to use iThenticate, but we host journals from all around Florida. If I were to use this plugin, my understanding is that they would also have access to all the other journals since they have the account. 
Is there a work around or an update in the future?  The folders wouldn't work for us  since we don't have the main account.

We are running OJS 3.3.0.5

**Comment by asmecher** [comment]
There is another issue filed for this, and I think your colleague has recently described your requirement there: https://github.com/asmecher/plagiarism/issues/8#issuecomment-921883785
