### ISSUE TITLE
Plugin failed to create folder

### ISSUE THREAD

**Issue by jonasraoni** [asmecher/plagiarism#15]
Hi!

The plugin is failing to create the folder due to a required parameter, so I had to create a [PR](https://github.com/bsobbe/iThenticate/pull/11) in another repository to address the error message.

I'll submit a PR soon. I had other comments to make, but I saw they are properly addressed in the issues.

**Comment by jonasraoni** [comment]
https://github.com/asmecher/plagiarism/pull/16

**Comment by jonasraoni** [comment]
@asmecher I forgot to update the package version :)
So, if you can do it and release a new tag, great \o/

As this plugin has a composer dependency, @mfelczak got curious how this plugin is installed through the plugin gallery. I didn't check yet, so I'm just commenting to ensure I didn't break the magic =]

**Comment by asmecher** [comment]
The plugin build tool knows to look for a `composer.json` file, and if it finds one, it runs Composer as part of the package build process. Those dependencies thus get automatically wrapped up in the `.tar.gz` file.
