### ISSUE TITLE
Plugin blocks submissions

### ISSUE THREAD

**Issue by mpbraendle** [asmecher/plagiarism#2]
The plugin seems to block submissions (Confirmation tab is empty and user can't continue).

I see the following in our Apache error log:

 PHP Fatal error:  require_once(): Failed opening required '/var/www/virtual/ojs.chimia.ch/htdocs/ojs/plugins/generic/plagiarism/vendor/autoload.php' (include_path='.:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/classes:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/pages:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/classes:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/pages:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/lib/adodb:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/lib/phputf8:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/lib/pqp/classes:/var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/lib/smarty:.:/usr/share/php:/usr/share/pear') in /var/www/virtual/ojs.chimia.ch/htdocs/ojs/plugins/generic/plagiarism/PlagiarismPlugin.inc.php on line 70, referer: https://ojs.chimia.ch/index.php/chimia/submission/wizard/4?submissionId=157

It looks like line 70 of PlagiarismPlugin.inc.php:

require_once(dirname(__FILE__) . '/vendor/autoload.php'); 

is the culprit

**Comment by asmecher** [comment]
@mpbraendle, how did you install this plugin? I suspect your Composer dependencies are missing.

**Comment by mpbraendle** [comment]
Downloaded a zip from GitHub. Ok, where do I get Composer? Thank you.

**Comment by asmecher** [comment]
@mpbraendle, I'd suggest installing the plugin from the Plugin Gallery. That'll take care of it for you.

**Comment by azamat5991** [comment]
Hi @asmecher ,

I have the same PHP Fatal error message because I've downloaded tar.gz from github and uploaded on my server. The issue is that I can't use Plugin Gallery since my hosting doesn't allow using tar command.
Is there any solution?
