### ISSUE TITLE
New Git tag / release is needed in order to include the latest commits

### ISSUE THREAD

**Issue by fradeve** [asmecher/plagiarism#20]
Hi @asmecher,
first things first, thanks for bringing to life this much-needed plugin :handshake: 

In the last few months a few PRs have been merged that include fixes that I would describe as critical for a few users.
In particular, issue #15 has been fixed that was preventing the plugin from working correctly, with a very obscure error that @jonasraoni kindly fixed.

Lots of automated build systems (including ours at Ubiquity Press) work by checking out the latest available release / Git tag, but the latest release of this plugin [goes back to Jan 2021](https://github.com/asmecher/plagiarism/releases/tag/v1_0_4-0), thus forcing build systems to either check out the latest commit on the `master` branch (which is not really safe as the content for master can change at any time if a new commit is pushed).

Is there any chance that a new release can be cut from the current `master`?
Thank you very much

**Comment by asmecher** [comment]
This is already in progress (https://github.com/asmecher/plagiarism/issues/18#issuecomment-1023519401).

**Comment by fradeve** [comment]
Thank you so much @asmecher @ewhanson :tada:

**Comment by fradeve** [comment]
Thank you very much @asmecher and @ewhanson, much appreciated! :pray:
