### ISSUE TITLE
Exclude bibliography check by default

### ISSUE THREAD

**Issue by israelcefrin** [asmecher/plagiarism#9]
Hi,

An Enterprise user of this plugin has enquired us whether the similarity check for newly submitted articles  could exclude bibliography by default.

It is something that could addressed as a new feature or an option to check if someone wants to include as well?

**Comment by asmecher** [comment]
@israelcefrin, is this a section of the uploaded file (e.g. typically the Word document) that's marked "Bibliography", or a separate file upload that should be excluded? Or something else?

**Comment by israelcefrin** [comment]
It would rely  on a section of the uploaded file (mostly word document) be marked as “bibliography” and excluded from the similarity check. This section doesn’t need to be marked as “Bibliography”, as iThenticate could identify such a section containing the reference list and excluded them per user settings. 
Only the manuscript should be uploaded. Currently the plugin uploads all files to iThenticate (including figure image files).  In fact only the manuscript text needs to run a plagiarism checking.

**Comment by mfelczak** [comment]
Hi @israelcefrin, is this something that the editors might be able to configure directly via their iThenticate settings, i.e. as suggested on pg 8 of their [user guide](https://www.ithenticate.com/hs-fs/hub/92785/file-1384442395-pdf/iTh_documentation/iThenticate_Manual.pdf):

> By invoking the relevant tick boxes you will be able to exclude quotes, bibliography, certain phrases you can set in the account settings, small matches and small sources

**Comment by israelcefrin** [comment]
Hi @mfelczak , thanks for the link. I will send it to the Editor to review their journal settings on the iThenticate dashboard.
